title: Exothermia
author: hisana
email: abby.kcs@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Security Researcher, Malware reverse engineer, Robot builder, Conservationist, Star gazer, Farmer.
  Threat Intelligence, Cybersecurity blogs.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: Apurva Kumar
  tagline: 
  date_format: "%b %-d, %Y"
  showNav: true
  style: red
  showPicker: false
  #To add comments
  #disqus_shortname: games
  texture:
  navigation:
    - title: Home
      url: "/"
    - title: Resume
      url: "/resume"
    - title: Blog
      url: "/blog"

  # generate social links in footer
  social_links:
    twitter: abby_kcs
    github:  hisana
    linkedIn: in/abby-kcs
    email: abby.kcs@gmail.com
  #  rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: thelehhman/texture


plugins:
  - jekyll-seo-tag
#  - jekyll-feed